dev:
  propel:
    param:
      classname:  DebugPDO

test:
  propel:
    param:
      classname:  DebugPDO

all:
  propel:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        'sqlite:%SF_DATA_DIR%/etva.db'
      encoding:   utf8
      persistent: true
      pooling:    true
