dev:
  propel:
    param:
      classname: DebugPDO
test:
  propel:
    param:
      classname: DebugPDO
all:
  propel:
    class: sfPropelDatabase
    param:
      classname: PropelPDO
      dsn: 'mysql:host=localhost;dbname=etva'
      username: etva_mysql
      password: pQX0CYoM
      encoding: utf8
      persistent: true
      pooling: true
