# default values
all:
  .array:
   # device interface for connectivity with CM and Agents
    device_interfaces:
      standard:
        cm_management: Management
        va_management: Management
        lan: LAN
      enterprise:
        cm_management: bond0
        va_management: Management
  # network interfaces hypervisor => driver supported
    interfaces:
      kvm:
       - rtl8139
       - e1000
       - virtio
      hvm:
       - xen
       - rtl8139
       - e1000
       
  # disks drivers hypervisor => driver supported
    disks:
      pv:
       - xen
       - ide
       - scsi
      hvm:
       - xen
       - ide
       - scsi
      kvm:
       - virtio
       - ide
       - scsi
  #
    fencingcmds:
      datacenter:
        fence_bladecenter: 'bladecenter'
        fence_virsh: 'virsh'
      node:
        fence_ilo: 'ilo'
        fence_ipmilan: 'ipmilan'
        fence_rsa: 'rsa'
    disk_formats:
        - raw
        - qcow2
        - qcow
        - cow
        - vmdk
  mac:
    default_first_octect: 0x00 #default first three octects for mac pool
    default_second_octect: 0x16
    default_third_octect: 0x3e
  node:
    monitor_keepalive: 15000 # miliseconds to perform monitor alive checks.
    monitor_keepalive_gap: 5000 # miliseconds between next node keepalive check.
    keepalive_update: 60 # seconds to perform update. Added offset (keepalive_update_offset)
                        # to add tolerance for comm delay..
    keepalive_update_offset: 30 # seconds of tolerance before change node state
  server:
    heartbeat_timeout_default: 180 # interval between heartbeat checks (in seconds)
    heartbeat_starttime: 300 # seconds of expected starting time
    heartbeat_number_of_restart: 3 # maximum number of restarts 

  setting:
    vnc_keymap: pt  # if not set in DB this will be used as default value
    eventlog_flush: 14  # remove event records after specified days (two weeks)
                       # if not set in DB this will be used as default value
    vnc_token_timeout: 3600 # timeout for vnc token
  volgroup:
    disk_flag: __DISK__ # disk flag used to identify volume group that contains only logical volumes that are files
  rra:
    dir: '%SF_DATA_DIR%/rra' 
  sf_guard_plugin:
    import_encrypted_passwords: true
  dbrequired: 1.2
  cron:
    alert_dir: '/var/run/etva_etvm'
    log_dir: '/var/log/etva_etvm'
  remote_log:
    file: '%SF_DATA_DIR%/diagnostic_ball.tgz'           # Diagnostic file
    script: '%SF_ROOT_DIR%/utils/diagnostic_ball.sh'    # Script that generates the file
    mailscript: '%SF_ROOT_DIR%/utils/pl/EmailLogs.pl'   # Script responsible for sending emails (with the diagnostic file attached)
    toemail: 'etva@eurotux.com' # rcpt to
  sshkey:
    pubfile: '%SF_ROOT_DIR%/.ssh/id_rsa.pub'
    privfile: '%SF_ROOT_DIR%/.ssh/id_rsa'

extdirect:
  ds_ext_direct_plugin:
        # Optional. Only use this parameter if you intend to create a mod_rewrite our route to a different URL for your extdirect front controller.
        #router_url: /extdirect.php

        # Optional. Set the javascript variable name for the js api spec (defaults to 'Ext.app.{YOUR_API_NAME}_API)
        #js_var: Ext.app.EXTDIRECT_API

        # Optional. Set a provider_type (defaults to remoting)
        #provider_type: remoting

 
