# default rules
  
dynamic_javascript:
   url: /djs
   param: { module: script}

signin:
  url: /login
  param: { module: sfGuardAuth, action: signin }

signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

updatesys:
  url: /updatesys
  module: { module: sfGuardAuth, action: updatesys }

default_index:
  url:   /:module
  param: { action: index }

xport_format:
  url:   /server/:action/:id.:sf_format
  param: { module: server }
  requirements:
    sf_format: (?:html|xml|json|js|png)

default:
  url:   /:module/:action/*

homepage:
  url:   /
  param: { module: view, action: index }
